title: AshKamdar Blog
description: > # ignore newlines until "baseurl:"
  In this blog, i will share my experiences working on new age things like Cloud, DevOps, CI/CD, DevSecOps along with Cloud-native and Micro-service architectures. 
  The current focus is technologies like Docker, Kubernetes, GitLab, Istio Service Mesh etc.
permalink: ':title/'
baseurl: "" # e.g. /blog
url: "https://ashkamdar.github.io/" # e.g. http://example.com
site-twitter: https://twitter.com/ash_kamdar #if your site has a twitter account, enter it here

# Author Settings
author: Ashish Kamdar
author-img: ashish-kamdar.png
about-author: DevOps with Kubernetes.

social-twitter: ash_kamdar
social-facebook:
social-github: AshKamdar
social-linkedin: ashkamdar/
social-email: ash.kamdar.blog@gmail.com

# Disqus
discus-identifier: https-ashkamdar-github-io

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "vendor"]
